//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroStoreProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    public partial class ProductDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDetail()
        {
            this.Carts = new HashSet<Cart>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public string ProdID { get; set; }
        public string ProdName { get; set; }
        public string ProdImage { get; set; }
        public Nullable<double> ProdPrice { get; set; }
        public Nullable<double> ProdMRP { get; set; }
        public Nullable<double> ProdSavings { get; set; }
        public Nullable<int> ProdQuantity { get; set; }
        public string isAvailable { get; set; }
        public string ProdCategory { get; set; }
        public string ProdCategoryID { get; set; }
        public string ProdDescription { get; set; }
        public Nullable<System.DateTime> ProdExpiryDate { get; set; }
        public string ProdSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public HttpPostedFileBase ProductImage { get; set; }
    }
}
